package edu.itc.salesreport.render;

import edu.itc.salesreport.model.BranchSummary;
import edu.itc.salesreport.model.MonthlyReport;
import edu.itc.salesreport.model.PaymentMethod;
import edu.itc.salesreport.model.ProductTotal;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * Modern HTML report renderer with responsive CSS styles, stat cards, and clean typography.
 */
public class HtmlReportRenderer implements ReportRenderer {

    @Override
    public void render(MonthlyReport report, Writer writer) throws IOException {
        PrintWriter out = new PrintWriter(writer);

        out.println("<!DOCTYPE html>");
        out.println("<html lang=\"en\">");
        out.println("<head>");
        out.println("  <meta charset=\"UTF-8\">");
        out.println("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        out.printf("  <title>Sales Report - %s</title>%n", report.month());
        out.println("  <style>");
        out.println("    :root {");
        out.println("      --primary: #2563eb;");
        out.println("      --bg: #f8fafc;");
        out.println("      --card-bg: #ffffff;");
        out.println("      --text-main: #0f172a;");
        out.println("      --text-muted: #64748b;");
        out.println("      --border: #e2e8f0;");
        out.println("      --success: #10b981;");
        out.println("      --warning: #f59e0b;");
        out.println("    }");
        out.println("    * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }");
        out.println("    body { background-color: var(--bg); color: var(--text-main); padding: 2rem; }");
        out.println("    .container { max-width: 1100px; margin: 0 auto; }");
        out.println("    header { margin-bottom: 2rem; border-bottom: 2px solid var(--border); padding-bottom: 1rem; }");
        out.println("    h1 { font-size: 2rem; color: #1e293b; }");
        out.println("    .subtitle { color: var(--text-muted); font-size: 1rem; margin-top: 0.25rem; }");
        out.println("    .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1.25rem; margin-bottom: 2.5rem; }");
        out.println("    .card { background: var(--card-bg); border-radius: 10px; padding: 1.25rem; border: 1px solid var(--border); box-shadow: 0 1px 3px rgba(0,0,0,0.05); }");
        out.println("    .card-title { font-size: 0.875rem; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-muted); font-weight: 600; }");
        out.println("    .card-val { font-size: 1.75rem; font-weight: 700; margin-top: 0.5rem; color: #0f172a; }");
        out.println("    .card-meta { font-size: 0.8125rem; color: var(--text-muted); margin-top: 0.25rem; }");
        out.println("    section { background: var(--card-bg); border-radius: 10px; border: 1px solid var(--border); padding: 1.5rem; margin-bottom: 2rem; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }");
        out.println("    h2 { font-size: 1.25rem; margin-bottom: 1rem; color: #1e293b; }");
        out.println("    table { width: 100%; border-collapse: collapse; text-align: left; }");
        out.println("    th { background: #f1f5f9; padding: 0.75rem 1rem; font-size: 0.875rem; color: #475569; font-weight: 600; border-bottom: 1px solid var(--border); }");
        out.println("    td { padding: 0.75rem 1rem; font-size: 0.875rem; border-bottom: 1px solid var(--border); }");
        out.println("    tr:last-child td { border-bottom: none; }");
        out.println("    .num { text-align: right; }");
        out.println("    .badge { display: inline-block; padding: 0.25rem 0.5rem; border-radius: 6px; font-size: 0.75rem; font-weight: 600; }");
        out.println("    .badge-cash { background: #e0f2fe; color: #0369a1; }");
        out.println("    .badge-card { background: #fef3c7; color: #b45309; }");
        out.println("    .badge-khqr { background: #dcfce7; color: #15803d; }");
        out.println("    footer { text-align: center; color: var(--text-muted); font-size: 0.875rem; margin-top: 2rem; }");
        out.println("  </style>");
        out.println("</head>");
        out.println("<body>");
        out.println("  <div class=\"container\">");
        out.println("    <header>");
        out.printf("      <h1>Monthly Sales Report</h1>%n");
        out.printf("      <p class=\"subtitle\">Period: %s &bull; Generated by edu.itc.salesreport</p>%n", report.month());
        out.println("    </header>");

        // Stat cards
        out.println("    <div class=\"stats-grid\">");
        out.println("      <div class=\"card\">");
        out.println("        <div class=\"card-title\">Total Revenue</div>");
        out.printf("        <div class=\"card-val\">$%,.2f</div>%n", report.totalRevenue());
        out.println("        <div class=\"card-meta\">All branches combined</div>");
        out.println("      </div>");
        out.println("      <div class=\"card\">");
        out.println("        <div class=\"card-title\">Transactions</div>");
        out.printf("        <div class=\"card-val\">%,d</div>%n", report.totalTransactions());
        out.printf("        <div class=\"card-meta\">%d invalid rows skipped</div>%n", report.invalidRowCount());
        out.println("      </div>");
        out.println("      <div class=\"card\">");
        out.println("        <div class=\"card-title\">Units Sold</div>");
        out.printf("        <div class=\"card-val\">%,d</div>%n", report.totalUnitsSold());
        out.println("        <div class=\"card-meta\">Individual items</div>");
        out.println("      </div>");
        out.println("      <div class=\"card\">");
        out.println("        <div class=\"card-title\">Files Ingested</div>");
        out.printf("        <div class=\"card-val\">%d</div>%n", report.totalFilesLoaded());
        out.println("        <div class=\"card-meta\">Daily CSV batches</div>");
        out.println("      </div>");
        out.println("    </div>");

        // Branch Breakdown Section
        out.println("    <section>");
        out.println("      <h2>Branch Performance</h2>");
        out.println("      <table>");
        out.println("        <thead>");
        out.println("          <tr>");
        out.println("            <th>Branch</th>");
        out.println("            <th class=\"num\">Transactions</th>");
        out.println("            <th class=\"num\">Units Sold</th>");
        out.println("            <th class=\"num\">Revenue</th>");
        out.println("            <th class=\"num\">Avg Tx Value</th>");
        out.println("          </tr>");
        out.println("        </thead>");
        out.println("        <tbody>");
        for (BranchSummary bs : report.branchSummaries()) {
            BigDecimal avg = bs.transactionCount() > 0
                    ? bs.totalRevenue().divide(BigDecimal.valueOf(bs.transactionCount()), 2, RoundingMode.HALF_UP)
                    : BigDecimal.ZERO;
            out.println("          <tr>");
            out.printf("            <td><strong>%s</strong></td>%n", bs.branch());
            out.printf("            <td class=\"num\">%,d</td>%n", bs.transactionCount());
            out.printf("            <td class=\"num\">%,d</td>%n", bs.totalUnitsSold());
            out.printf("            <td class=\"num\">$%,.2f</td>%n", bs.totalRevenue());
            out.printf("            <td class=\"num\">$%,.2f</td>%n", avg);
            out.println("          </tr>");
        }
        out.println("        </tbody>");
        out.println("      </table>");
        out.println("    </section>");

        // Payment Method Section
        out.println("    <section>");
        out.println("      <h2>Payment Method Breakdown</h2>");
        out.println("      <table>");
        out.println("        <thead>");
        out.println("          <tr>");
        out.println("            <th>Method</th>");
        out.println("            <th class=\"num\">Total Collected</th>");
        out.println("            <th class=\"num\">Market Share</th>");
        out.println("          </tr>");
        out.println("        </thead>");
        out.println("        <tbody>");
        for (PaymentMethod pm : PaymentMethod.values()) {
            BigDecimal rev = report.totalRevenueByPaymentMethod().getOrDefault(pm, BigDecimal.ZERO);
            BigDecimal share = report.totalRevenue().compareTo(BigDecimal.ZERO) > 0
                    ? rev.multiply(BigDecimal.valueOf(100)).divide(report.totalRevenue(), 1, RoundingMode.HALF_UP)
                    : BigDecimal.ZERO;
            String badgeClass = switch (pm) {
                case CASH -> "badge-cash";
                case CARD -> "badge-card";
                case KHQR -> "badge-khqr";
            };
            out.println("          <tr>");
            out.printf("            <td><span class=\"badge %s\">%s</span></td>%n", badgeClass, pm);
            out.printf("            <td class=\"num\">$%,.2f</td>%n", rev);
            out.printf("            <td class=\"num\">%.1f%%</td>%n", share);
            out.println("          </tr>");
        }
        out.println("        </tbody>");
        out.println("      </table>");
        out.println("    </section>");

        // Top Products Section
        out.println("    <section>");
        out.println("      <h2>Top Performing Products</h2>");
        out.println("      <table>");
        out.println("        <thead>");
        out.println("          <tr>");
        out.println("            <th>SKU</th>");
        out.println("            <th>Product Name</th>");
        out.println("            <th>Category</th>");
        out.println("            <th class=\"num\">Units Sold</th>");
        out.println("            <th class=\"num\">Total Revenue</th>");
        out.println("          </tr>");
        out.println("        </thead>");
        out.println("        <tbody>");
        int count = 0;
        for (ProductTotal pt : report.topProducts()) {
            if (++count > 10) break;
            out.println("          <tr>");
            out.printf("            <td><code>%s</code></td>%n", pt.sku());
            out.printf("            <td>%s</td>%n", pt.productName());
            out.printf("            <td>%s</td>%n", pt.category());
            out.printf("            <td class=\"num\">%,d</td>%n", pt.totalQuantitySold());
            out.printf("            <td class=\"num\">$%,.2f</td>%n", pt.totalRevenue());
            out.println("          </tr>");
        }
        out.println("        </tbody>");
        out.println("      </table>");
        out.println("    </section>");

        out.println("    <footer>");
        out.println("      <p>&copy; 2026 Sales Report System - Team 11. Built with Java 21+ &amp; Clean Architecture.</p>");
        out.println("    </footer>");
        out.println("  </div>");
        out.println("</body>");
        out.println("</html>");
        out.flush();
    }
}
